version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fastdb
      - POSTGRES_USER=fastuser
      - POSTGRES_PASSWORD=password
    volumes:
      - fastapi_pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  api:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENV=local
      - POSTGRES_URI=postgres://fastuser:password@db/fastdb
      - REDIS_URI=redis://redis:6379

  redis:
    image: redis:alpine

volumes:
  fastapi_pgdata: